#+TITLE: HLI345 Final Paper -- Literature Review
#+SUBTITLE: Moral, Scientific, and Religious Perspectives on the Bargain in /Doctor Faustus/
#+STARTUP: noindent showall
#+OPTIONS: toc:nil num:nil
#+DATE: 16 Nov 2018
#+LaTeX_HEADER: \usepackage[1.0in]{geometry}

* Goals and Direction of Final Paper
For my research, I intend to address the interaction between morality, Christian values and themes, and the pursuit of knowledge as seen in Christopher Marlowe's /The Tragical History of the Life and Death of Doctor Faustus/, with a focus on the bargain with the devil and what it entailed. As we were able to discuss in lecture, Marlowe blends comedy and tragedy in this tale to preach the dangers of hubris, being unaware of one's place and limitations, and neglecting repentance in favor of stubbornness. He makes a deal with Lucifer, brokered by Mephistopheles, and because of the aforementioned fatal flaws, Doctor Faustus meets a grim and unforgiving end. However, beyond the surface level themes posed in the drama, Marlowe additionally offers a thorough look into the temporal context in which the tale was penned. Though the tale was clearly blasphemous by the standards of the Elizabethan society of the time it was written, /Doctor Faustus/ was able to show us the conflict that sometimes arises between science and religion, and how these two forces make it difficult to determine the morality of human action.

After an individual analysis of each perspective on the bargain (moral, scientific, and religious), I wish to describe the interaction of all the perspectives. The tale did not formally take the side of either Lucifer or God, nor did it attempt to choose between religion or science. Marlowe simply described the plight of Doctor Faustus, and it is left to the audience to ask these questions of themselves. With my paper, I hope to provide an inquisitive audience with more tools to understand how the pursuit of knowledge and the values of Christianity butt heads in Doctor Faustus, and how they contribute to the question of determining the moral parity of the bargain, and whether or not it was ill-intentioned.

* Intended Reference Literature
** [[https://www.jstor.org/stable/pdf/518380.pdf?refreqid=excelsior%3A1bdcc318f53f2fb72f2fecb30dd0bd5e][Faustus and the Apple]]
This paper, though short, offers valuable perspectives on different justifications of Doctor Faustus's actions. It compares Doctor Faustus's pursuit of knowledge to the forbidden apple in the biblical Garden of Eden. This paper aptly describes the precise actions and moments in the text that damn Doctor Faustus, and under which ideologies he is damned. It takes a more objective view on the bargain, contesting against the typical understanding that Doctor Faustus's bargain was foolish. It factors in consciousness of the sin and its ramifications, as well as intent, in determination of the morality of the bargain. These considerations provide the kind of holistic view I wished to present in my paper, so this reference will surely be a valuable asset.
** [[https://search.proquest.com/docview/1424322802/fulltext/143D9FCB4C2D4A8CPQ/1?accountid=14052][Faustus, Confession, and the Sins of Omission]]
Parker's work in this reference focuses specifically on two things: the role of confession in absolving Faustus of his sins, and the biblical quotations that Doctor Faustus makes throughout the drama. It poses the viewpoint that Lucifer as represented in /Doctor Faustus/ has more in common with humanity as we know it than Christ ever could, which further combats the conventional belief that Doctor Faustus acted in error when agreeing to the bargain. However, this reference also highlights that the selectivity of Doctor Faustus's biblical quotes are selfish, in that they paint him in a very forgivable, understandable light from a human perspective. It says that his omission of biblical quotes that would hurt his stance, and re-contextualization of the quotes that he /did/ use, hurt the argument that the bargain was justifiable. Similar to the article above, this reference provides a multi-faceted approach to judging Doctor Faustus, paying particular attention to the Christian perspective.
** [[https://link.springer.com/article/10.1007/s00146-012-0411-5][Doctor Faustus in the twenty-first century]]
This 2012 work by Douglas Schuler provides a modern perspective on morality as perceived through the lens of this work, and provides a thorough analysis of the bargain. Given that the reference offers a re-contextualization of /Doctor Faustus/ with more modern values, it provides supporting arguments and information for the scientific view that I intend to detail in my paper. It also describes the analogues to Faustian bargains that we make today, and how we can use similar strategies of judgment for reviewing Doctor Faustus's actions as we do for those analogues in our day-to-day lives.
** [[https://www.jstor.org/stable/2872271?seq=1#metadata_info_tab_contents][Christian Belief in Doctor Faustus]]
Despite the fact that this reference is quite dated, it still offers a valuable look at the religious perspective in /Doctor Faustus/. Like Parker, O'Brien decrees in this paper that Doctor Faustus's selective biblical quotation and misinterpretation helps him to internally justify the actions leading up to his damnation. To O'Brien, Faustus deceives himself with his false understanding of scripture. Since the entirety of /Doctor Faustus/ is wrought with references to the Christian understanding of divinity, this work allows us to judge the bargain from that perspective. It reminds us of his opportunities to repent and that the religious Christians of Marlowe's time would have condemned Doctor Faustus and praised that he paid witness to the vengeance of God in the end.
** [[https://www.jstor.org/stable/370963?seq=1#metadata_info_tab_contents][The Tragedy of Marlowe's /Doctor Faustus/]]
In this reference, Mizener makes the argument that Faustus is meant to earn our pity for making the bargain, rather than our condemnation. Mizener offers that Faustus makes great sacrifices when making the bargain with Lucifer, though the reader or viewer is distracted by how fervently he pursues his desires. As his realization of the nature of his damnation grows over time, he is left to divert his attention with simple manipulations of the sensuous world. This reference allows us to view the bargain from the sympathetic perspective of human desire, and further make moral justifications for the bargain, under the argument that Doctor Faustus behaved just as humans do, and he is as much a born sinner as the rest of us; making it an apt tool to support the analysis I intend to provide in my research.

* Other Reference Literature in Consideration
** [[https://www.jstor.org/stable/2871873?seq=1#metadata_info_tab_contents][The Comic Synthesis in Doctor Faustus]]
** [[https://www.jstor.org/stable/449293?seq=1#metadata_info_tab_contents][The Orthodox Christian Framework of Marlowe's Faustus]]
** [[https://www.jstor.org/stable/1261310?seq=1#metadata_info_tab_contents][Marlowe and God: The Tragic Theology of Dr. Faustus]]
