#+TITLE: HLI345 Final
#+STARTUP: noindent showall
#+OPTIONS: toc:nil num:nil
#+DATE: 12 Dec 2018
#+LaTeX_HEADER: \usepackage[1.0]{geometry}

*Consider the two "con artists" Tartuffe and Horner. One succeeds -- more or less -- with his con while the other one does not. What are the competing messages Molière and Wycherley are offering? Are there any significant similarities between the two? What do we gain by analyzing these two plays together?*
--------

Molière and Wycherley both sculpt their comedies around a miscreant. These characters, Tartuffe and Horner, are both frauds, scheming to elevate their status by taking advantage of the shortcomings of those around them. While the two characters each have a different dénouement, their tales share similarities that convey similar messages to the audience. At first glance, a reader may believe that since Molière's Tartuffe failed in his exploits and Wycherley's Horner succeeded, it means that the former does not condone the behavior and the latter does. While this may be true, the actual message that the tales convey is up for debate. It is certain that by the end of the tales, Tartuffe is made the fool by King Louis XIV, and Horner is victorious in reaping the fruits of his ruse indefinitely. However, after a careful reading, one might come to the conclusion that the ending holds less weight toward the message of the comedy than expected.

We can begin by assessing what the comedies do and do not have in commmon. In both of the tales, the "hero" is able to pull the wool over the eyes of those around him. They know how to display their intentions in a favorable light, and are able to leverage the naïveté of those that they wish to extort. In /Tartuffe/, the titular character is able to fool Orgon and his mother with ease. He acts with piety and speaks as a man of God, and is thus able to win them over.

Horner's con in /The Country Wife/ is more elaborate, but in the same way, he is able to convince the men in town that he means no harm and can entertain their wives without their need to worry. These skillful cons rely on more than just the incompetency of the other characters; the characters needed to exercise care to ensure that their true intentions were not discovered. Though in /Tartuffe/, Orgon and his family are rescued by /deus ex machina/, the victims in /The Country Wife/ do not earn this luxury, and Horner is able to continue his trickery through the end of the tale.

Beyond the differences in the story, there are also some stark differences in the behavior of the characters, which may indicate a difference in the intent of the author. Though Horner and Tartuffe are both con artists, Tartuffe is outwardly malicious in his behavior. When Orgon discovers his ill-intentions, he replies: "You're the one to leave, acting like the master. Now I'll make it known, the full disaster: The house belongs to me, yes, all of it... But I know how to really punish you. Those who harm me, they know not what they do." Molière punishes Tartuffe for his high-headedness about his victory, but Wycherley rewards Horner for maintaining his composure throughout his ruse. Horner simply sought his pleasure and did not rub his success in the face of his victims. Hence, it shows that Molière, rather than punishing the con, is punishing the hubris. Meanwhile, Wycherley is rewarding Horner for simply pursuing his desires.

By analyzing these two plays together, we are able to see that the true sin is not in pursuing illicit desires, but rather in self-righteousness and cockiness. Though each author portrays a man of ill-character, we can see that one enjoys a different fate than the other. As is the case with many classic drama we have studied, hubris is the greatest sin that man can get involved in.
